config/routes.rb
Rails.application.routes.draw do

  

  resources :users do
    collection do 
      get :search_user
    end
  end

  resources :static_pages do 
    collection do
      get :home
    end
 end

  root            'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activation, only:[:edit]
  resources :password_resets,  only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :microposts do
  resources :comments
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController #it means StaticPagesController inherited from Rails class ApplicationController 
  
  def index
  
  end

  def home
    if logged_in?
  @micropost=current_user.microposts.build 
  @feed_items=current_user.feed.paginate(page:params[:page])
    end
  end

  def help
  	
  end
  def about
  	
  end
  def contact
  	 
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
  Tutorial</em></a> is a
  <a href="http://www.railstutorial.org/book">book</a> and
  <a href="http://screencasts.railstutorial.org/">screencast series</a>
  to teach web development with
  <a href="http://rubyonrails.org/">Ruby on Rails</a>.

  This is the sample application is developed  using rails tutorials.

  This is the sample application for the tutorial.

</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>

<div class="help">
<h1><%=  image_tag "images.jpeg", alt: "Help Logo" %></h1>
<p class="bold">
  Get help on the Ruby on Rails Tutorial at the Rails Tutorial help section.
 <!--  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>. -->
  To get help on this Rails app, see the
  <a href="http://www.railstutorial.org/book" class="bold"><em>Ruby on Rails Tutorial</em>
  book</a>.
  <ul class="bold">
  	<li>To login to this site first you have to register.For registeration go to Signup page <%= link_to "Sign up now!", signup_path%></li>
  <li>If user is already registered then go to Login page<%= link_to  " Login now!", users_path %></li>
  <li>If User forget his/her password then click on froget password link on login page <%= link_to  " Login now!", users_path %></li>
  <li>After login you will redirect to Users page where all users are listout.</li>
  <li>Click on Home you will go to home page of Logged in user.</li>
  <li>Click on Account link you will listout with three another option<ol><li> Profile</li><li>Settings</li><li>Logout</li></ol></li>
  <li>Click on Profile User Profile page will open.</li>
  <li>Click on Settings Updation page will open.</li>
  <li>Click on Logout User will Logged out.</li>
</p>
</div>

app/views/static_pages/home.html.erb
<!--<h1>Sample App</h1>
=======
<h1>Sample App</h1>
>>>>>>> statis-pages
<p>
  This is the home page for the
  <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
<<<<<<< HEAD
</p>-->
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
      <section class="stats">
         <%= render 'shared/stats' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to the Rails tweet</h1>

  <!-- <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    Rails application.
  </h2> -->

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>
            <% end %>

</p>

<SCRIPT TYPE="text/javascript">
    $(".cmt_button").click(function(){
        var id =$(this).attr("id")
        $("#"+id+"div").toggle();
        // $('.comment').toggle();
    });
    
</SCRIPT>

app/views/static_pages/index.html.erb
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
this is index page
<%=link_to "home", home_static_pages_path%>